ALTER AVAILABILITY GROUP App1 
MODIFY REPLICA ON N'CLUSTERNODE1\PRIMARYREPLICA' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=(('CLUSTERNODE4\READ01',’CLUSTERNODE5\READ02’),(‘CLUSTERNODE6\READ03’,’CLUSTERNODE7\READ04’)))) ;
